# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer
    - name: Build Package
      run: swift build
    - name: Test Package
      run: swift test
    - name: Check SDKs
      run: xcodebuild -showsdks
    - name: Build Example Project macOS & iOS
      run: cd Example && xcodebuild -configuration Release -scheme Example -sdk macosx CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
    - name: Build iOS
      run: cd Example && xcodebuild -configuration Release -scheme Example -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
